swagger: '2.0'
info:
  version: v1.0
  title: Hanzo Marketing
  description: >
    Hanzo Marketing provides a set of APIs for running many sorts of
    marketing campaigns - including referral marketing, affiliate marketing,
    and traditional ad campaigns.
host: api.hanzo.io
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.io/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

# 'x-headers':
#   - key: Authorization
#     value: SANDBOXTOKEN

'x-send-defaults':    false
'x-explorer-enabled': false
'x-proxy-enabled':    false
'x-samples-enabled':  true
'x-samples-languages':
  - curl
  - node
  - go
  - java
  - php
  - python
  - ruby
  - swift

# See other .yaml files for full definition
