swagger: '2.0'
info:
  version: v1.0
  title: Hanzo Identity
  description: >
    Hanzo Identity provides a set of APIs for building and managing users
    their data.
host: api.hanzo.io
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.io/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

# See other .yaml files for full definition
